version: '3'

services:
  openldap:
    build: .
    environment:
      - LDAP_ORGANISATION=Mon Organisation
      - LDAP_DOMAIN=mondomaine.com
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_TLS=true
      - LDAP_TLS_CRT_FILENAME=ldap.crt
      - LDAP_TLS_KEY_FILENAME=ldap.key
      - LDAP_TLS_CA_CRT_FILENAME=ca.crt
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      - ./certs:/container/service/slapd/assets/certs
    networks:
      - ldap_network

networks:
  ldap_network:

volumes:
  ldap_data:
  ldap_config:
