version: '3.8'

services:
  openldap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - "LDAP_BASE_DN=dc=ldapsae,dc=com"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=ldapsae.com.ca.crt
    networks:
      - openldap

  php:
    build: ./php
    container_name: php
    ports:
    - 8087:80
    - 8443:443
    depends_on:
      - openldap
    volumes:
      - ./php:/var/www/html
      - ./php/src/certs/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./php/src/certs/localhost.key:/etc/ssl/private/localhost.key  
    networks:
      - openldap

  db:
    image: mariadb
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - openldap

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "8080:80"
    links:
      - db
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.sae.localhost`)"
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.tls=true"
    networks:
      - openldap
  
  sql-database-service:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: saeldap
      MYSQL_USER: admin
      MYSQL_PASSWORD: ${SQL_DATABASE_PASSWORD}
    ports: 
      - "3306:3306"
    volumes: 
      - ./Scripts/sql-init-scripts:/docker-entrypoint-initdb.d
      - mysql_data:/val/lib/mysql
    networks:
      - openldap

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: sql-database-service 
      PMA_PORT: 3306
    ports:
      - "8081:80" 
    depends_on:
      - sql-database-service 
    networks:
      - openldap

  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME: keycloak.sae.localhost
      KC_PROXY: edge
    command: 
      - start-dev 
      - --import-realm
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.sae.localhost`)"
      - "traefik.http.routers.keycloak.tls=true"
    volumes:
      - ./keycloak/realm.json:/opt/keycloak/data/import/realm.json
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8082:8080"
    networks:
      - openldap

  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:4.5.0
    restart: always
    volumes:
      - ./data/uploads:/app/uploads
      - rocketchat_data:/var/lib/rocket.chat
    environment:
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0"
      ROOT_URL: "https://rocket.sae.localhost"
      ADMIN_USERNAME: "Uadmin"
      ADMIN_NAME: "Uadmin"
      ADMIN_PASS: "passadmin"
      ADMIN_EMAIL: "admin@example.com"
      OVERWRITE_SETTING_Show_Setup_Wizard: completed
      # Configuration LDAP
      # OVERWRITE_SETTING_LDAP_Enable: "true"
      # OVERWRITE_SETTING_LDAP_Authentication: "true"
      # OVERWRITE_SETTING_LDAP_Authentication_UserDN: "cn=admin,dc=ldapsae,dc=com"
      # OVERWRITE_SETTING_LDAP_Authentication_Password: "passadmin"
      # OVERWRITE_SETTING_LDAP_Host: "openldap"
      # OVERWRITE_SETTING_LDAP_Port: "389"
      # OVERWRITE_SETTING_LDAP_BaseDN: "dc=ldapsae,dc=com"
      # OVERWRITE_SETTING_LDAP_Find_After_Login: "true"
      # OVERWRITE_SETTING_LDAP_BindSearchPassword: "passadmin"
      # OVERWRITE_SETTING_LDAP_User_Search_Filter: "(objectclass=*)"
      # OVERWRITE_SETTING_LDAP_AD_User_Search_Field: "uid"
      # OVERWRITE_SETTING_LDAP_AD_Username_Field: "uid"
      # OVERWRITE_SETTING_LDAP_Sync_User_Data: "true"
      # OVERWRITE_SETTING_LDAP_Deafault_Domain: "ldapsae.com"
      # OVERWRITE_SETTING_Accounts_TwoFactorAuthentication_Enabled: "false"
      # Configuration keycloak
      Accounts_OAuth_Custom_Keycloak: "true"
      Accounts_OAuth_Custom_Keycloak_url: "http://localhost:8082"
      Accounts_OAuth_Custom_Keycloak_token_path: "/realms/sae-services/protocol/openid-connect/token"
      Accounts_OAuth_Custom_Keycloak_token_sent_via: "header"
      Accounts_OAuth_Custom_Keycloak_identity_token_sent_via: "header"
      Accounts_OAuth_Custom_Keycloak_identity_path: "/realms/sae-services/protocol/openid-connect/userinfo"
      Accounts_OAuth_Custom_Keycloak_authorize_path: "/realms/sae-services/protocol/openid-connect/auth"
      Accounts_OAuth_Custom_Keycloak_scope: "openid"
      Accounts_OAuth_Custom_keycloak_access_token_param: "access_token"
      Accounts_OAuth_Custom_Keycloak_id: "rocket-chat"
      Accounts_OAuth_Custom_Keycloak_secret: ${ROCKET_CHAT_CLIENT_SECRET}
      Accounts_OAuth_Custom_Keycloak_login_style: "redirect"
      Accounts_OAuth_Custom_Keycloak_button_label_text: "Login via Keycloak"
      Accounts_OAuth_Custom_Keycloak_button_label_color: "#FFFFFF"
      Accounts_OAuth_Custom_Keycloak_button_color: "#13679A"
      Accounts_OAuth_Custom_Keycloak_username_field: "preferred_username"
      Accounts_OAuth_Custom_Keycloak_merge_users: "false"
      OVERWRITE_SETTING_Accounts_TwoFactorAuthentication_Enabled: "false"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rocketchat-app.rule=Host(`rocket.sae.localhost`)"
      - "traefik.http.routers.rocketchat-app.tls=true"
      - "traefik.http.routers.rocketchat.entrypoints=https"
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - openldap


  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    restart: unless-stopped
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 7017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: true
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - openldap

  #nginx-proxy:
  #    image: nginx:latest
  #    container_name: nginx-proxy
  #    ports:
      #   - "80:80" 
      # volumes:
      #   - ./nginx:/etc/nginx/conf.d
      #   - ./nginx/certs:/etc/nginx/certs
      # depends_on:
      #   - openldap
      #   - php
      #   - phpldapadmin
      #   - db
      #   - nextcloud
      #   - sql-database-service
      #   - phpmyadmin
      # networks:
      #   - openldap   


  reverse-proxy:
    image: traefik:v2.3
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config.yml:/etc/traefik/config.yml:ro
      - ./traefik/certs/sae.localhost.crt:/etc/certs/sae.localhost.crt:ro
      - ./traefik/certs/sae.localhost.key:/etc/certs/sae.localhost.key:ro
    networks:
      - openldap
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik=true"
      - "traefik.docker.network=openldap"


volumes:
  rocketchat_data:
  mongodb_data:
  ldap_data:
  ldap_config:
  db_data:
  nextcloud_data:
  mysql_data:
  keycloak_data:

networks:
  openldap:
    external: true
