version: '3.8'

services:
  openldap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openldap
    hostname: openldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./data/certificates:/container/service/slapd/assets/certs
      - ./data/slapd/database:/var/lib/ldap
      - ./data/slapd/config:/etc/ldap/slapd.d
    environment:
      - LDAP_ADMIN_PASSWORD=passadmin
      - "LDAP_BASE_DN=dc=ldapsae,dc=com"
      - LDAP_TLS_CRT_FILENAME=server.crt
      - LDAP_TLS_KEY_FILENAME=server.key
      - LDAP_TLS_CA_CRT_FILENAME=ldapsae.com.ca.crt
    networks:
      - openldap

  php:
    build: ./php
    ports:
    - 80:80
    - 443:443
    depends_on:
      - openldap
    volumes:
      - ./php:/var/www/html
      - ./php/src/certs/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./php/src/certs/localhost.key:/etc/ssl/private/localhost.key   
    networks:
      - openldap

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    hostname: phpldapadmin
    ports:
      - "90:80"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    depends_on:
      - openldap
    networks:
      - openldap

  db:
    image: mariadb
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_PASSWORD=nextcloudpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - openldap

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "8080:80"
    links:
      - db
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloudpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    networks:
      - openldap
  
  sql-database-service:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saeldap
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports: 
      - "3306:3306"
    volumes: 
      - ./Scripts/sql-init-scripts:/docker-entrypoint-initdb.d
      - mysql_data:/val/lib/mysql
    networks:
      - openldap

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: sql-database-service 
      PMA_PORT: 3306
    ports:
      - "8081:80" # Expose it on a different port if 8080 is already in use
    depends_on:
      - sql-database-service 
    networks:
      - openldap
    
volumes:
  ldap_data:
  ldap_config:
  db_data:
  nextcloud_data:
  mysql_data:

networks:
  openldap:

