version: '3.8'

services:
  
  db:
    image: mariadb
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sae

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "8082:80"
    links:
      - db
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.sae.localhost`)"
    #  - "traefik.http.routers.nextcloud.entrypoints=https"
    #  - "traefik.http.routers.nextcloud.tls=true"
    networks:
      - sae

  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:4.5.0
    restart: always
    volumes:
      - ./data/uploads:/app/uploads
      - rocketchat_data:/var/lib/rocket.chat
    environment:
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0"
      ROOT_URL: "http://localhost:3000"
      ADMIN_USERNAME: "Uadmin"
      ADMIN_NAME: "Uadmin"
      ADMIN_PASS: ${ADMIN_PASS}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      OVERWRITE_SETTING_Show_Setup_Wizard: completed
      # Configuration LDAP
      # OVERWRITE_SETTING_LDAP_Enable: "true"
      # OVERWRITE_SETTING_LDAP_Authentication: "true"
      # OVERWRITE_SETTING_LDAP_Authentication_UserDN: "cn=admin,dc=ldapsae,dc=com"
      # OVERWRITE_SETTING_LDAP_Authentication_Password: "passadmin"
      # OVERWRITE_SETTING_LDAP_Host: "openldap"
      # OVERWRITE_SETTING_LDAP_Port: "389"
      # OVERWRITE_SETTING_LDAP_BaseDN: "dc=ldapsae,dc=com"
      # OVERWRITE_SETTING_LDAP_Find_After_Login: "true"
      # OVERWRITE_SETTING_LDAP_BindSearchPassword: "passadmin"
      # OVERWRITE_SETTING_LDAP_User_Search_Filter: "(objectclass=*)"
      # OVERWRITE_SETTING_LDAP_AD_User_Search_Field: "uid"
      # OVERWRITE_SETTING_LDAP_AD_Username_Field: "uid"
      # OVERWRITE_SETTING_LDAP_Sync_User_Data: "true"
      # OVERWRITE_SETTING_LDAP_Deafault_Domain: "ldapsae.com"
      # OVERWRITE_SETTING_Accounts_TwoFactorAuthentication_Enabled: "false"
      # Configuration keycloak
      Accounts_OAuth_Custom_Keycloak: "true"
      Accounts_OAuth_Custom_Keycloak_url: "http://keycloak:8080"
      Accounts_OAuth_Custom_Keycloak_token_path: "/realms/sae-services/protocol/openid-connect/token"
      Accounts_OAuth_Custom_Keycloak_token_sent_via: "header"
      Accounts_OAuth_Custom_Keycloak_identity_token_sent_via: "header"
      Accounts_OAuth_Custom_Keycloak_identity_path: "/realms/sae-services/protocol/openid-connect/userinfo"
      Accounts_OAuth_Custom_Keycloak_authorize_path: "/realms/sae-services/protocol/openid-connect/auth"
      Accounts_OAuth_Custom_Keycloak_scope: "openid"
      Accounts_OAuth_Custom_keycloak_access_token_param: "access_token"
      Accounts_OAuth_Custom_Keycloak_id: "rocket-chat"
      Accounts_OAuth_Custom_Keycloak_secret: ${ROCKET_CHAT_CLIENT_SECRET}
      Accounts_OAuth_Custom_Keycloak_login_style: "redirect"
      Accounts_OAuth_Custom_Keycloak_button_label_text: "Login via Keycloak"
      Accounts_OAuth_Custom_Keycloak_button_label_color: "#FFFFFF"
      Accounts_OAuth_Custom_Keycloak_button_color: "#13679A"
      Accounts_OAuth_Custom_Keycloak_username_field: "preferred_username"
      Accounts_OAuth_Custom_Keycloak_merge_users: "false"
      OVERWRITE_SETTING_Accounts_TwoFactorAuthentication_Enabled: "false"
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.rocketchat-app.rule=Host(`rocket.sae.localhost`)"
    #  - "traefik.http.routers.rocketchat-app.tls=true"
    #  - "traefik.http.routers.rocketchat.entrypoints=https"
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    networks:
      - sae


  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    restart: unless-stopped
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 7017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: true
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - sae


volumes:
  rocketchat_data:
  mongodb_data:
  db_data:
  nextcloud_data:


networks:
  sae:
    external: true
